version: '3.1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      SA_PASSWORD: "C0ntrol1*"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always
    container_name: Examen1_SQL
volumes:
  mssql-data:
    driver: local